### ISSUE TITLE
IOException: No such file or directory

### ISSUE THREAD

**Issue by siruma** [siruma/SensorDataLabeller#19]
IOException: No such file or directory
device: Polar M600

`Caused by: java.io.IOException: No such file or directory
                                                                                                    	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
                                                                                                    	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
                                                                                                    	at java.io.File.createNewFile(File.java:1000)
                                                                                                    	at com.sensordatalabeler.MainActivity.openFile(MainActivity.kt:188)
                                                                                                    	at com.sensordatalabeler.MainActivity.onClickSensorLabeler(MainActivity.kt:164)`

**Comment by siruma** [comment]
Closes by #20
